### ISSUE TITLE
Parking meter interaction

### ISSUE THREAD

**Issue by eseguraca6** [CityofSantaMonica/Orchard.ParkingData#43]
I have a question. I want to study parking networks and transactions. How can I interact with the parking meter to execute a transaction myself, from an app rather than physically?

**Comment by thekaveman** [comment]
By _execute a transaction_ - are you talking about e.g. adding value to the meter or otherwise pushing data into the system? 

As currently defined, this API is for **read** purposes, and really only for the 2 sensor event types at meters. We do not make **writes** available, and I suspect that will not change any time soon.

Could you give a little more background on what you are trying to look at and/or accomplish?

**Comment by eseguraca6** [comment]
So, essentially, say I want to pay for my parking from my phone; from what I am reading, if I am not mistaken, that would not be possible, correct, for me to pay from the phone and thus paying the parking?

**Comment by thekaveman** [comment]
Correct, that is not possible via this API.
